"""Собрать ОДИН Vegas-скрипт, который глушит две аудиодорожки разными движками.

Идея пользователя: в проект Vegas добавляются ДВЕ звуковые дорожки (одна и та же
дорожка/файл, продублированная). Скрипт:
  - на 1-й аудиодорожке   -> мутит диапазоны из decisions_gigaam.json
  - на 2-й аудиодорожке   -> мутит диапазоны из decisions_whisperx.json
Так можно на слух сравнить оба движка в одном проекте, переключая соло дорожек.

Перекодирования НЕТ. Тот же клип: каждый мат-диапазон разрезается на 3 события,
у среднего FadeIn.Gain=0 (абсолютная тишина). Разрезается ТОЛЬКО целевая дорожка.

Тайминги берутся из готовых decisions_*.json (stream_start/stream_end — абсолютное
время во всём stream.mp4), заново ничего не транскрибируется.

Запуск:
    backend\.venv\Scripts\python backend\examples\build_dual_track_vegas.py ^
        --dir work\_asr_probe_15min

Порядок дорожек по умолчанию: track#1 = GigaAM, track#2 = WhisperX.
Меняется флагом --order whisperx,gigaam.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def load_ranges(decisions_path: Path) -> list[tuple[float, float]]:
    """Достаём (stream_start, stream_end) из decisions.json, отбрасывая
    не-экспортируемые статусы (как это делает прод-экспорт)."""
    data = json.loads(decisions_path.read_text(encoding="utf-8"))
    mutes = data.get("mutes")
    if not isinstance(mutes, list):
        raise ValueError(f"{decisions_path}: нет массива 'mutes'")
    skip = {"rejected", "deleted", "disabled", "review"}
    ranges: list[tuple[float, float]] = []
    for m in mutes:
        if m.get("action", "MUTE") != "MUTE":
            continue
        if m.get("status", "accepted") in skip:
            continue
        s = float(m["stream_start"])
        e = float(m["stream_end"])
        if e > s:
            ranges.append((s, e))
    ranges.sort()
    return ranges


def cs_array(ranges: list[tuple[float, float]]) -> str:
    """C#-инициализатор double[,] { {s,e}, ... }."""
    if not ranges:
        return "new double[0, 2]"
    rows = ",\n".join(f"            {{ {s:.3f}, {e:.3f} }}" for s, e in ranges)
    return "new double[,] {\n" + rows + "\n        }"


def generate(order: list[tuple[str, list[tuple[float, float]]]]) -> str:
    """order — список (label, ranges) в порядке аудиодорожек (0-я, 1-я, ...)."""
    lines: list[str] = [
        "// Generated by twitch_cut — DUAL-TRACK compare.",
        "// Мутит РАЗНЫЕ аудиодорожки РАЗНЫМИ движками для сравнения на слух.",
        "// Ничего не перекодирует: split + FadeIn.Gain=0 на целевой дорожке.",
        "//",
        "// Раскладка аудиодорожек (сверху вниз, только IsAudio):",
    ]
    for i, (label, rng) in enumerate(order):
        lines.append(f"//   audio-track #{i + 1}: {label}  ({len(rng)} mute)")
    lines.extend(
        [
            "using System;",
            "using System.Collections.Generic;",
            "using System.Windows.Forms;",
            "using ScriptPortal.Vegas;",
            "",
            "public class EntryPoint",
            "{",
            "    public void FromVegas(Vegas vegas)",
            "    {",
        ]
    )

    # Массивы диапазонов на каждую аудиодорожку
    for i, (label, rng) in enumerate(order):
        lines.append(f"        // --- audio-track #{i + 1}: {label} ---")
        lines.append(f"        double[,] ranges{i} = {cs_array(rng)};")
    lines.append("")

    # Собираем список аудиодорожек по порядку
    lines.extend(
        [
            "        List<Track> audioTracks = new List<Track>();",
            "        foreach (Track t in vegas.Project.Tracks)",
            "        {",
            "            if (t.IsAudio()) audioTracks.Add(t);",
            "        }",
            "",
            f"        int needed = {len(order)};",
            "        if (audioTracks.Count < needed)",
            "        {",
            "            MessageBox.Show(\"Нужно минимум \" + needed + \" аудиодорожки, а есть \" "
            "+ audioTracks.Count + \".\\nДобавь вторую звуковую дорожку и запусти снова.\");",
            "            return;",
            "        }",
            "",
        ]
    )
    for i in range(len(order)):
        lines.append(f"        ApplyRanges(audioTracks[{i}], ranges{i});")

    lines.extend(
        [
            "    }",
            "",
            "    // Мутит все диапазоны на ОДНОЙ дорожке.",
            "    private void ApplyRanges(Track track, double[,] ranges)",
            "    {",
            "        for (int i = 0; i < ranges.GetLength(0); i++)",
            "        {",
            "            SilenceRangeOnTrack(track, ranges[i, 0], ranges[i, 1]);",
            "        }",
            "    }",
            "",
            "    // Разрезает события целевой дорожки на границах [start,end] и глушит середину.",
            "    private void SilenceRangeOnTrack(Track track, double start, double end)",
            "    {",
            "        List<TrackEvent> evs = new List<TrackEvent>();",
            "        foreach (TrackEvent e in track.Events) evs.Add(e);",
            "",
            "        foreach (TrackEvent e in evs)",
            "        {",
            "            double es = e.Start.ToMilliseconds() / 1000.0;",
            "            double ee = e.End.ToMilliseconds() / 1000.0;",
            "            if (ee <= start || es >= end) continue;",
            "",
            "            TrackEvent mid = e;",
            "            if (es < start) mid = e.Split(Timecode.FromSeconds(start - es));",
            "",
            "            double ms = mid.Start.ToMilliseconds() / 1000.0;",
            "            double me = mid.End.ToMilliseconds() / 1000.0;",
            "            if (me > end) mid.Split(Timecode.FromSeconds(end - ms));",
            "",
            "            AudioEvent ae = mid as AudioEvent;",
            "            if (ae != null) ae.FadeIn.Gain = 0f;",
            "        }",
            "    }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Один Vegas-скрипт: две дорожки, два движка")
    ap.add_argument("--dir", type=Path, required=True,
                    help="папка с decisions_gigaam.json и decisions_whisperx.json")
    ap.add_argument("--gigaam", type=Path, default=None,
                    help="путь к decisions_gigaam.json (по умолчанию --dir/decisions_gigaam.json)")
    ap.add_argument("--whisperx", type=Path, default=None,
                    help="путь к decisions_whisperx.json")
    ap.add_argument("--order", default="gigaam,whisperx",
                    help="порядок дорожек сверху вниз, из {gigaam,whisperx}")
    ap.add_argument("--out", type=Path, default=None,
                    help="куда писать .cs (по умолчанию --dir/vegas_dual_track.cs)")
    args = ap.parse_args()

    gj = args.gigaam or (args.dir / "decisions_gigaam.json")
    wj = args.whisperx or (args.dir / "decisions_whisperx.json")
    out = args.out or (args.dir / "vegas_dual_track.cs")

    ranges = {
        "gigaam": load_ranges(gj),
        "whisperx": load_ranges(wj),
    }
    labels = {"gigaam": "GigaAM", "whisperx": "WhisperX"}

    order_keys = [k.strip().lower() for k in args.order.split(",") if k.strip()]
    for k in order_keys:
        if k not in ranges:
            raise SystemExit(f"--order: неизвестный движок {k!r}, можно только gigaam/whisperx")

    order = [(labels[k], ranges[k]) for k in order_keys]
    out.write_text(generate(order), encoding="utf-8")

    print("Готово. Один скрипт на две дорожки:")
    for i, k in enumerate(order_keys):
        print(f"  audio-track #{i + 1}: {labels[k]:9} — {len(ranges[k])} mute")
    print(f"\n  -> {out}")
    print("\nКак пользоваться в Vegas Pro:")
    print("  1. Импортируй stream.mp4. Продублируй аудио так, чтобы было ДВЕ звуковые")
    print("     дорожки с одним и тем же аудио (просто скопируй событие на новую audio-track).")
    print(f"  2. Порядок сверху вниз: #1 = {labels[order_keys[0]]}, #2 = {labels[order_keys[1]]}.")
    print("  3. Tools -> Scripting -> Run Script -> выбери vegas_dual_track.cs")
    print("  4. Соло-переключай дорожки и слушай, чей мут точнее.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
