"""Мульти-паддинг проба для GigaAM: один Vegas-скрипт, где КАЖДАЯ аудиодорожка —
это тот же набор матов, но с РАЗНЫМ before-паддингом. Слушаешь соло и выбираешь,
на каком значении атака слова ("б" в "блять") перестаёт проскакивать, но мут ещё
не лезет на соседнее слово.

БЕЗ перетранскрипции и перекодирования: берём raw_stream_start/raw_stream_end
(тайминги слова ДО паддинга) из готового decisions_gigaam.json и заново применяем
только паддинг. after-паддинг фиксирован (хвост у GigaAM и так тугой).

Запуск:
    backend\.venv\Scripts\python backend\examples\build_padding_probe_vegas.py ^
        --decisions work\_asr_probe_15min\decisions_gigaam.json ^
        --before 80,130,180 --after 120

Раскладка дорожек сверху вниз соответствует порядку --before.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def load_raw_ranges(decisions_path: Path) -> list[tuple[float, float]]:
    """(raw_stream_start, raw_stream_end) в секундах — граница СЛОВА до паддинга,
    только для экспортируемых статусов."""
    data = json.loads(decisions_path.read_text(encoding="utf-8"))
    mutes = data.get("mutes")
    if not isinstance(mutes, list):
        raise ValueError(f"{decisions_path}: нет массива 'mutes'")
    skip = {"rejected", "deleted", "disabled", "review"}
    out: list[tuple[float, float]] = []
    for m in mutes:
        if m.get("action", "MUTE") != "MUTE":
            continue
        if m.get("status", "accepted") in skip:
            continue
        rs = m.get("raw_stream_start")
        re = m.get("raw_stream_end")
        if rs is None or re is None:
            # fallback на финальные тайминги, если raw нет
            rs, re = m["stream_start"], m["stream_end"]
        rs = float(rs)
        re = float(re)
        if re > rs:
            out.append((rs, re))
    out.sort()
    return out


def apply_padding(raw: list[tuple[float, float]], before_ms: int, after_ms: int,
                  max_word_s: float = 1.5) -> list[tuple[float, float]]:
    """Применяем паддинг как в проде + word-cap, затем склеиваем пересечения."""
    before = before_ms / 1000.0
    after = after_ms / 1000.0
    padded: list[tuple[float, float]] = []
    for s, e in raw:
        dur = e - s
        if dur > max_word_s:      # хвостовое слово с раздутым end — обрезаем
            e = s + max_word_s
        ns = max(0.0, s - before)
        ne = e + after
        padded.append((ns, ne))
    padded.sort()
    # склейка пересекающихся/касающихся диапазонов на одной дорожке
    merged: list[list[float]] = []
    for s, e in padded:
        if merged and s <= merged[-1][1]:
            merged[-1][1] = max(merged[-1][1], e)
        else:
            merged.append([s, e])
    return [(s, e) for s, e in merged]


def cs_array(ranges: list[tuple[float, float]]) -> str:
    if not ranges:
        return "new double[0, 2]"
    rows = ",\n".join(f"            {{ {s:.3f}, {e:.3f} }}" for s, e in ranges)
    return "new double[,] {\n" + rows + "\n        }"


def generate(tracks: list[tuple[str, list[tuple[float, float]]]]) -> str:
    lines: list[str] = [
        "// Generated by twitch_cut — PADDING PROBE (GigaAM).",
        "// Каждая аудиодорожка = те же маты, но с РАЗНЫМ before-паддингом.",
        "// Ничего не перекодирует: split + FadeIn.Gain=0 на своей дорожке.",
        "//",
        "// Раскладка аудиодорожек (сверху вниз, только IsAudio):",
    ]
    for i, (label, rng) in enumerate(tracks):
        lines.append(f"//   audio-track #{i + 1}: {label}  ({len(rng)} mute)")
    lines.extend(
        [
            "using System;",
            "using System.Collections.Generic;",
            "using System.Windows.Forms;",
            "using ScriptPortal.Vegas;",
            "",
            "public class EntryPoint",
            "{",
            "    public void FromVegas(Vegas vegas)",
            "    {",
        ]
    )
    for i, (label, rng) in enumerate(tracks):
        lines.append(f"        // --- audio-track #{i + 1}: {label} ---")
        lines.append(f"        double[,] ranges{i} = {cs_array(rng)};")
    lines.append("")
    lines.extend(
        [
            "        List<Track> audioTracks = new List<Track>();",
            "        foreach (Track t in vegas.Project.Tracks)",
            "        {",
            "            if (t.IsAudio()) audioTracks.Add(t);",
            "        }",
            "",
            f"        int needed = {len(tracks)};",
            "        if (audioTracks.Count < needed)",
            "        {",
            "            MessageBox.Show(\"Нужно минимум \" + needed + \" аудиодорожки (по одной "
            "на вариант паддинга), а есть \" + audioTracks.Count + \".\\nСкопируй аудио на \" + "
            "needed + \" дорожки и запусти снова.\");",
            "            return;",
            "        }",
            "",
        ]
    )
    for i in range(len(tracks)):
        lines.append(f"        ApplyRanges(audioTracks[{i}], ranges{i});")
    lines.extend(
        [
            "    }",
            "",
            "    private void ApplyRanges(Track track, double[,] ranges)",
            "    {",
            "        for (int i = 0; i < ranges.GetLength(0); i++)",
            "            SilenceRangeOnTrack(track, ranges[i, 0], ranges[i, 1]);",
            "    }",
            "",
            "    private void SilenceRangeOnTrack(Track track, double start, double end)",
            "    {",
            "        List<TrackEvent> evs = new List<TrackEvent>();",
            "        foreach (TrackEvent e in track.Events) evs.Add(e);",
            "        foreach (TrackEvent e in evs)",
            "        {",
            "            double es = e.Start.ToMilliseconds() / 1000.0;",
            "            double ee = e.End.ToMilliseconds() / 1000.0;",
            "            if (ee <= start || es >= end) continue;",
            "            TrackEvent mid = e;",
            "            if (es < start) mid = e.Split(Timecode.FromSeconds(start - es));",
            "            double ms = mid.Start.ToMilliseconds() / 1000.0;",
            "            double me = mid.End.ToMilliseconds() / 1000.0;",
            "            if (me > end) mid.Split(Timecode.FromSeconds(end - ms));",
            "            AudioEvent ae = mid as AudioEvent;",
            "            if (ae != null) ae.FadeIn.Gain = 0f;",
            "        }",
            "    }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Мульти-паддинг проба GigaAM в один Vegas-скрипт")
    ap.add_argument("--decisions", type=Path, required=True,
                    help="decisions_gigaam.json из прошлого прогона")
    ap.add_argument("--before", default="80,130,180",
                    help="список before-паддингов в мс через запятую (по дорожке на каждый)")
    ap.add_argument("--after", type=int, default=120, help="after-паддинг, мс (общий)")
    ap.add_argument("--out", type=Path, default=None)
    args = ap.parse_args()

    befores = [int(x) for x in args.before.split(",") if x.strip()]
    raw = load_raw_ranges(args.decisions)
    out = args.out or (args.decisions.parent / "vegas_gigaam_padding_probe.cs")

    tracks: list[tuple[str, list[tuple[float, float]]]] = []
    for b in befores:
        rng = apply_padding(raw, b, args.after)
        tracks.append((f"GigaAM before={b}ms after={args.after}ms", rng))

    out.write_text(generate(tracks), encoding="utf-8")

    print(f"Слов-матов (raw): {len(raw)}")
    print("Один скрипт, дорожки сверху вниз:")
    for i, (label, rng) in enumerate(tracks):
        print(f"  audio-track #{i + 1}: {label:38} — {len(rng)} mute (после склейки)")
    print(f"\n  -> {out}")
    print("\nВ Vegas:")
    print(f"  1. Сделай {len(tracks)} звуковые дорожки с одним и тем же аудио (копия события).")
    print("  2. Tools -> Scripting -> Run Script -> vegas_gigaam_padding_probe.cs")
    print("  3. Соло-переключай дорожки на одном и том же мате и слушай:")
    print("     - где 'б' в 'блять' перестаёт проскакивать (before достаточно большой)")
    print("     - где мут НЕ начал глушить соседнее слово (before не слишком большой)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
