from __future__ import annotations

from pathlib import Path
from typing import Any


class VegasExportError(ValueError):
    """Raised when decisions.json cannot be exported to Vegas script."""


def csharp_string(value: str) -> str:
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n') + '"'


def exportable_mutes(decisions: dict[str, Any]) -> list[dict[str, Any]]:
    """Return editable mute decisions that should become Vegas audio edits."""

    mutes = decisions.get("mutes")
    if mutes is None:
        raise VegasExportError("decisions.json must contain a 'mutes' array")
    if not isinstance(mutes, list):
        raise VegasExportError("decisions.json field 'mutes' must be an array")

    result: list[dict[str, Any]] = []
    for index, mute in enumerate(mutes):
        if not isinstance(mute, dict):
            raise VegasExportError(f"mutes[{index}] must be an object")
        if mute.get("action", "MUTE") != "MUTE":
            continue
        if mute.get("status", "accepted") in {"rejected", "deleted", "disabled", "review"}:
            continue
        if "stream_start" not in mute or "stream_end" not in mute:
            raise VegasExportError(f"mutes[{index}] must contain stream_start and stream_end")
        start = float(mute["stream_start"])
        end = float(mute["stream_end"])
        if end <= start:
            raise VegasExportError(f"mutes[{index}] has stream_end <= stream_start")
        result.append(mute)
    return result


def generate_vegas_script(decisions: dict[str, Any]) -> str:
    """Generate a Vegas Pro C# script that mutes profanity ranges.

    Design decisions (важно, не менять без нужды):
      - Никаких Region'ов / Marker'ов: пользователь просил чистый timeline.
      - Мут делаем НЕ через свойство ``TrackEvent.Mute = true`` (это ставит флаг
        на весь клип), а через splice + ``FadeIn.Gain = 0``: разрезаем событие
        на границах диапазона и у среднего кусочка опускаем гейн фейда в 0
        (эквивалент абсолютной тишины на этом фрагменте).
      - После обработки перегруппировываем события: аудио- и видео-событие с
        (почти) одинаковым Start попадают в один ``TrackEventGroup``, чтобы
        нарезка не разъезжалась при последующем drag'n'drop'е.

    Итог: тот же аудиофайл, но каждый profanity-диапазон разрезан на 3 события;
    среднее — с ``FadeIn.Gain = 0`` (тишина). Парные события (аудио+видео)
    склеены обратно в единые группы.
    """

    lines = [
        "// Generated by twitch_cut Phase 5.",
        "// Splits audio events at profanity boundaries and silences the middle",
        "// piece by dropping its gain to 0. Groups all resulting tracks into one",
        "// TrackGroup. Does NOT create regions or markers.",
        "using System;",
        "using System.Collections.Generic;",
        "using ScriptPortal.Vegas;",
        "",
        "public class EntryPoint",
        "{",
        "    public void FromVegas(Vegas vegas)",
        "    {",
    ]

    mutes = exportable_mutes(decisions)
    for mute in mutes:
        start = float(mute["stream_start"])
        end = float(mute["stream_end"])
        lines.append(f"        SilenceAudioRange(vegas, {start:.3f}, {end:.3f});")

    # Regroup — после всех разрезов, чтобы новые события тоже попали в группы.
    lines.append("        RegroupPairs(vegas);")

    lines.extend(
        [
            "    }",
            "",
            "    private void SilenceAudioRange(Vegas vegas, double start, double end)",
            "    {",
            "        foreach (Track track in vegas.Project.Tracks)",
            "        {",
            "            List<TrackEvent> evs = new List<TrackEvent>();",
            "            foreach (TrackEvent e in track.Events) evs.Add(e);",
            "",
            "            foreach (TrackEvent e in evs)",
            "            {",
            "                double es = e.Start.ToMilliseconds() / 1000.0;",
            "                double ee = e.End.ToMilliseconds() / 1000.0;",
            "                if (ee <= start || es >= end) continue;",
            "",
            "                TrackEvent mid = e;",
            "                if (es < start) mid = e.Split(Timecode.FromSeconds(start - es));",
            "                ",
            "                double ms = mid.Start.ToMilliseconds() / 1000.0;",
            "                double me = mid.End.ToMilliseconds() / 1000.0;",
            "                if (me > end) mid.Split(Timecode.FromSeconds(end - ms));",
            "",
            "                // Старый добрый способ проверки типа без 'is'",
            "                AudioEvent ae = mid as AudioEvent;",
            "                if (ae != null)",
            "                {",
            "                    ae.FadeIn.Gain = 0f;",
            "                }",
            "            }",
            "        }",
            "    }",
            "",
            "    private void RegroupPairs(Vegas vegas)",
            "    {",
            "        vegas.Project.Groups.Clear();",
            "        foreach (Track t1 in vegas.Project.Tracks)",
            "        {",
            "            foreach (TrackEvent e1 in t1.Events)",
            "            {",
            "                foreach (Track t2 in vegas.Project.Tracks)",
            "                {",
            "                    if (t1 == t2) continue;",
            "                    foreach (TrackEvent e2 in t2.Events)",
            "                    {",
            "                        // Если ивенты перекрываются более чем на 90%, считаем их парой",
            "                        // Это спасает от ошибок округления времени",
            "                        double startDiff = Math.Abs(e1.Start.ToMilliseconds() - e2.Start.ToMilliseconds());",
            "                        if (startDiff < 10) ",
            "                        {",
            "                            TrackEventGroup g = new TrackEventGroup();",
            "                            vegas.Project.Groups.Add(g);",
            "                            g.Add(e1);",
            "                            g.Add(e2);",
            "                        }",
            "                    }",
            "                }",
            "            }",
            "        }",
            "    }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def write_vegas_script(path: Path, decisions: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(generate_vegas_script(decisions), encoding="utf-8")
